### ISSUE TITLE
lazygit does not use tmTheme

### ISSUE THREAD

**Issue by LukePeltier** [rebelot/kanagawa.nvim#265]
Hi,

I'm not sure if this is because of older support or miscommunication, but lazygit does not support the tmTheme file type. 

Can the documentation be updated to reflect this?

Can we get a lazygit config which _does_ use the theme? https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#color-attributes

**Comment by KhoaLee** [comment]
Late comment but hope it helps other persons: 
```yml
# Kanagawa Wave
    activeBorderColor:
      - "#7e9cd8"
      - "bold"
    inactiveBorderColor:
      - "#54546d"
    searchingActiveBorderColor:
      - "#e6c384"
      - "bold"
    optionsTextColor:
      - "#957fb8"
    selectedLineBgColor:
      - "#2d4f67"
    inactiveViewSelectedLineBgColor:
      - "#1f1f28"
    cherryPickedCommitFgColor:
      - "#7e9cd8"
    cherryPickedCommitBgColor:
      - "#2d4f67"
    markedBaseCommitFgColor:
      - "#e6c384"
    markedBaseCommitBgColor:
      - "#2d4f67"
    unstagedChangesColor:
      - "#c34043"
    defaultFgColor:
      - "#dcd7ba"

# Kanagawa Dragon
   activeBorderColor:
     - "#8ba4b0"
     - "bold"
   inactiveBorderColor:
     - "#625e5a"
   searchingActiveBorderColor:
     - "#c4b28a"
     - "bold"
   optionsTextColor:
     - "#8992a7"
   selectedLineBgColor:
     - "#282727"
   inactiveViewSelectedLineBgColor:
     - "#1d1c19"
   cherryPickedCommitFgColor:
     - "#8ba4b0"
   cherryPickedCommitBgColor:
     - "#282727"
   markedBaseCommitFgColor:
     - "#c4b28a"
   markedBaseCommitBgColor:
     - "#282727"
   unstagedChangesColor:
     - "#c4746e"
   defaultFgColor:
     - "#c5c9c5"
```
